---
- hosts: web
  become: yes
  gather_facts: no
  
  vars_prompt:
    name: password
    prompt: Inupt password for new users
    
  tasks:
    - name: add users
      user:
        name: "{{ item }}"
        password: "{{ password | password_hash('sha512') }}"
      loop:
        - user01
        - user02
        - user03
