---
- hosts: web
  become: yes
  gather_facts: no

  tasks:
    - name: uninstall httpd
      yum:
        name: httpd
        state: absent

    - name: remove
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/httpd/
        - /var/www
