---
- hosts: web
  become: yes
  gather_facts: no

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest

    - name: deploy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: configure Listen Port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80$'
        line: 'Listen 8080'
        validate: httpd -tf %s
      notify:
        - restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
        enabled: yes