---
- hosts: XXX
  become: yes
  gather_facts: no

  tasks:
    - name: install httpd
      yum:
        name: XXX
        state: XXX

    - name: deploy index.html
      XXX:
        src: XXX
        dest: /var/www/html/index.html

    - name: configure Listen Port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80$'
        line: XXX
        validate: httpd -tf %s
      notify:
        - restart httpd

  handlers:
    - name: restart httpd
      XXX:
        name: httpd
        state: XXX
        enabled: yes
